INCLUDE_DIR = ../include/
CC     		= gcc
CFLAGS 		= -Wall -Wextra -Werror -g -I $(INCLUDE_DIR)

NAME = shell
SRC  = shell utils
SRCS = $(addsuffix .c, $(SRC))
OBJS = $(addsuffix .o, $(SRC))

OBJS_DIR      = objs/
OBJS_PREFIXED = $(addprefix $(OBJS_DIR), $(OBJS))

$(OBJS_PREFIXED): $(SRCS)
	mkdir -p $(OBJS_DIR)
	$(CC) $(CFLAGS) -c $(SRCS)
	mv *.o $(OBJS_DIR)

$(NAME): $(OBJS_PREFIXED)
	$(CC) $(CFLAGS) $(OBJS_PREFIXED) main.c -o $(NAME)

all: $(NAME)
	mv $(NAME) ../

clean:
	rm -rf $(OBJS_DIR)

fclean: clean
	rm -f ../$(NAME)

re: clean all